services:
  ebook_converter_bot:
    container_name: ebook_converter_bot
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    command: uv run -m ebook_converter_bot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    volumes:
      - "./:/app"
